language: ruby
sudo: false
cache: bundler
rvm:
  - 2.6
env:
  global:
    - COVERAGE=1
    - JRUBY_OPTS=''
    - RUBYOPT='-W0'
  matrix:
    - RESQUE='~> 2.0.0'

matrix:
  fast_finish: true
services:
  - redis-server
before_install:
  - sudo sed -e 's/^bind.*/bind 127.0.0.1/' /etc/redis/redis.conf > redis.conf
  - sudo mv redis.conf /etc/redis
  - sudo service redis-server start
  - echo PING | nc localhost 6379
script:
  - bundle exec rake
addons:
  apt:
    packages:
      - redis-server
